/* Kingdom 2000 — apply live figures from data/kingdom.json.
   The file is generated by tools/build-data.js from the MightPulse API.

   Everything here degrades: if the file is missing, stale, or malformed, the page keeps the
   figures written into the HTML and nothing breaks. That matters — a recruitment page that
   renders empty boxes because a third-party API had a bad morning is worse than one showing
   last week's numbers. */

(async function () {
  let d;
  try {
    const res = await fetch("data/kingdom.json", { cache: "no-cache" });
    if (!res.ok) return;
    d = await res.json();
  } catch { return; }
  if (!d || !d.kingdom) return;

  const M = n => (n || n === 0) ? n.toFixed ? n.toFixed(1) + " M" : n + " M" : null;
  const set = (key, value) => {
    if (value === null || value === undefined) return;
    document.querySelectorAll(`[data-live="${key}"]`).forEach(el => { el.textContent = value; });
  };

  /* ---- registry plate and overview facts ---- */
  const k = d.kingdom;
  set("ageDays",       k.ageDays ? k.ageDays + " d" : null);
  set("openedOn",      k.openedOn);
  set("activeGovs",    k.active7d ? "~" + k.active7d.toLocaleString("en-US") : null);
  set("allianceCount", k.allianceCount);
  set("floor100",      M(k.floor100));
  set("kingdomPower",  M(k.power));
  set("powerRank",     k.powerRank ? "#" + k.powerRank : null);

  /* ---- alliance leaderboard ---- */
  // The API knows power, not KvK points or weekly movement — relabel rather than fake them.
  document.querySelectorAll('[data-live-head="share"]').forEach(e => { e.textContent = "Power share"; });
  document.querySelectorAll('[data-live-head="trend"]').forEach(e => { e.textContent = "Top-10 floor"; });

  const rows = document.getElementById("lbRows");
  if (rows && Array.isArray(d.leaderboard) && d.leaderboard.length) {
    const byTag = Object.fromEntries((d.alliances || []).map(a => [a.tag, a]));
    const total = d.leaderboard.reduce((s, a) => s + (a.power || 0), 0) || 1;
    rows.innerHTML = d.leaderboard.map(a => {
      const meta = byTag[a.abbr] || {};
      const share = Math.round(((a.power || 0) / total) * 100);
      return `
        <div class="r">
          <div class="pos">${a.pos}</div>
          <div class="who"><b>${esc(a.abbr)}</b><em>${esc(meta.name || a.name || "")}</em></div>
          <div class="n">${M(a.power)}</div>
          <div class="n">${meta.members ?? "—"} / 100</div>
          <div class="n"><span class="crown">${meta.crowns ?? "—"}</span></div>
          <div class="n">${share}%<span class="bar"><i style="width:${share * 3}%"></i></span></div>
          <div class="tr fl">${meta.top10 ? meta.top10.toFixed(1) + " M" : "—"}</div>
        </div>`;
    }).join("");
  }

  /* ---- placement estimator ---- */
  if (Array.isArray(d.alliances) && typeof window.applyLiveAlliances === "function") {
    const usable = d.alliances.filter(a => a.bands && a.bands.length);
    if (usable.length) window.applyLiveAlliances(usable);
  }

  /* ---- freshness stamp, with attribution and a visible staleness flag ---- */
  const when = new Date(d.generatedAt);
  const stamp = when.toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
  const ageDays = (Date.now() - when.getTime()) / 86400000;
  // The refresh runs daily. Past 3 days something has stopped — say so rather than
  // silently showing an old number as if it were current.
  const staleNote = ageDays > 3
    ? ` <b style="color:#8A2A2A">This has not updated in ${Math.floor(ageDays)} days — the automatic
        refresh may be stuck. Numbers below may be out of date.</b>`
    : "";
  document.querySelectorAll("[data-live-stamp]").forEach(el => {
    el.innerHTML = `Power, rosters and alliance ranks refreshed ${stamp} from
      <a href="https://mightpulse.com/" rel="noopener">MightPulse</a>, an independent, unofficial
      Kingshot fan site — not affiliated with Century Games.${staleNote} KvK results, the NAP,
      buff schedule, event times and open seats are maintained by hand and dated separately.`;
  });

  function esc(s) {
    return String(s).replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
  }
})();
